### ISSUE TITLE
[Bug]: yt-dlp subtitle transcript without support for multi language videos

### ISSUE THREAD

**Issue by gocasimiro** [danielmiessler/Fabric#1667]
### What happened?

When I try to use the yt command in videos which language aren't in english (portuguese in my case) yt-dlp returns the following log
`yt-dlp failed: exit status 1, stderr: ERROR: Unable to download video subtitles for 'en': HTTP Error 429: Too Many Requests`
I have my fabric --setup language reset to default
This used to work regardless of video language, any tips?
Thanks!

### Operating System

macOS - Silicon (arm64)

### OS Version

```shell
ProductName:            macOS
ProductVersion:         15.6
BuildVersion:           24G84
```

### How did you install Fabric?

Release Binary - macOS (arm64)

### Version

```text
v1.4.272
```

### Relevant log output

```shell
yt-dlp failed: exit status 1, stderr: ERROR: Unable to download video subtitles for 'en': HTTP Error 429: Too Many Requests
```

**Comment by TioGlo** [comment]
I'm getting similar behavior on ubuntu 24.04. 

go installation

### Version
```
v1.4.272
```
### Log output
```
yt-dlp failed: exit status 1, stderr: 

ERROR: Did not get any data blocks
```

**Comment by ksylvan** [comment]
@TioGlo @gocasimiro Can you send me a Youtube link I can reproduce it with so I can make a fix?

**Comment by Lukas-tek-no-logic** [comment]
Hello,
this is same problem I described in:
https://github.com/danielmiessler/Fabric/issues/1665

Here is example of video that throws error:

"https://www.youtube.com/watch?v=5TSsAllb8BI&pp=0gcJCccJAYcqIYzv"

**Comment by ksylvan** [comment]
@Twozee-Tech Looks like a YouTube throttling issue.

https://github.com/yt-dlp/yt-dlp/issues/13831

**Comment by ksylvan** [comment]
And also see this, @Twozee-Tech https://www.reddit.com/r/youtubedl/comments/1mdk3dh/comment/n64lkcf/

**Comment by ksylvan** [comment]
I've added some new functionality to the YouTube extraction code.

See this: https://github.com/danielmiessler/Fabric/discussions/1682

@Twozee-Tech @gocasimiro - It might not fix your rate-limiting issue, but it makes it possible to use browser cookies and other capabilities of `yt-dlp`

**Comment by gocasimiro** [comment]
I'll test and let you know as soon as I can. Thank you so much for your support @ksylvan! It means a lot

**Comment by ksylvan** [comment]
@gocasimiro @Twozee-Tech see the new document here too:

https://github.com/ksylvan/fabric/blob/main/docs/YouTube-Processing.md

**Comment by Lukas-tek-no-logic** [comment]
Hi, im out camping with family for few days. I'll test as soon as I get back.
Thanks for support!

**Comment by grabanton** [comment]
Hey @ksylvan , I also have rate limit issue, but when tried to use flag --yt-dlp-args got the error from fabric:

fabric -y "https://www.youtube.com/watch?v=88M9FNmeZGw" --yt-dlp-args "--cookies-from-browser vivaldi"
expected argument for flag `--yt-dlp-args', but got option `--cookies-from-browser vivaldi'
expected argument for flag `--yt-dlp-args', but got option `--cookies-from-browser vivaldi'

fabric -y "https://www.youtube.com/watch?v=88M9FNmeZGw" --yt-dlp-args "--sleep-requests 1"
expected argument for flag `--yt-dlp-args', but got option `--sleep-requests 1'
expected argument for flag `--yt-dlp-args', but got option `--sleep-requests 1'

probably https://github.com/ksylvan/fabric/blob/main/docs/YouTube-Processing.md  is out of date?

**Comment by ksylvan** [comment]
@grabanton 

The message was wrong. The issue has been corrected in the latest version; please use it as follows (note the `=` between the flag and its multi-word argument):

```bash
fabric -y "https://www.youtube.com/watch?v=88M9FNmeZGw" --yt-dlp-args="--cookies-from-browser vivaldi"
```

**Comment by kobalt0801** [comment]
Have what seems to be part of the same issue, but slightly different.  I am getting the following error:


```
$ fabric -y "https://www.youtube.com/watch?v=rKp2dAOA6Hs" --pattern summarize
yt-dlp failed with language 'en' and fallback. Original error: 

ERROR: Did not get any data blocks
. Fallback error: 

ERROR: Did not get any data blocks
```

Running this inside a debian 12 VM in Proxmox.  Fresh install via Go.

**Comment by DevAbdoTolba** [comment]
Did not fix for me
(even after installing the latest version now
```cmd
fabric /y https://www.youtube.com/watch?v=SYJ5sattsmw&list=PLvGpI5t1gJ8QBXD00hjpdYbH8ozN0ntE2&index=3 --yt-dlp-args="--cookies-from-browser vivaldi"

YouTube rate limit exceeded. Try again later or use different yt-dlp arguments like '--sleep-requests 1' to slow down requests. Error: exit status 1
'list' is not recognized as an internal or external command,
operable program or batch file.
'index' is not recognized as an internal or external command,
operable program or batch file.
```


and

```cmd
fabric /y https://www.youtube.com/watch?v=88M9FNmeZGw --yt-dlp-args="--cookies-from-browser vivaldi"

yt-dlp failed with language 'en' and fallback. Original error: ERROR: could not find vivaldi cookies database in "C:\<location somewhere>\Vivaldi\User Data"
. Fallback error: ERROR: could not find vivaldi cookies database in "C:\<location somewhere>\Vivaldi\User Data"
```

**Comment by ecliPze507** [comment]
I got the same issue as DevAbdoTolba using the latest version running on Windows on bare metal:

```
 fabric -y https://www.youtube.com/watch?v=vs5cmGQWEEk --yt-dlp-args='--cookies-from-browser firefox'
YouTube rate limit exceeded. Try again later or use different yt-dlp arguments like '--sleep-requests 1' to slow down requests. Error: exit status 1
```

**Comment by ksylvan** [comment]
Unfortunately, @ecliPze507  @DevAbdoTolba That looks like YouTube rate limiting and you might want to look at the `yt-dlp` repository for issues around that. If they find a workaround, we will immediately benefit.

**Comment by FELIPEGUEDESBR** [comment]
This works for me:
fabric -y https://youtu.be/wA4_xTKqrgc --pattern summarize -- --sleep-requests 2
